import { StatusNotice } from '../../components/status-notice.tsx'
import { ConnectionLogo } from './models/service-logo.tsx'
import { SettingRow, SettingsGroup } from '../../components/settings-layout.tsx'
import { useRef, useState } from 'react'
import { useQuery } from '@tanstack/react-query'
import { CheckCircle2, Circle, CircleAlert, Plus, Search, Settings2, TriangleAlert } from 'lucide-react'
import type { ModelRoute } from '../../../../../packages/rp-core/src/types.ts'
import type { ModelCheck } from '../../../../../apps/server/src/services/model-inspection.ts'
import { CancelButton, EditorForm } from '../../components/form-guard.tsx'
import { ModelPicker } from '../../components/selectors.tsx'
import { Button, Empty, ErrorNotice, Input, Loading, Menu, MenuItem, MenuLabel, MenuSeparator, Modal, TabGroup } from '../../components/ui.tsx'
import { api, useAction, useModels } from '../../lib/api.ts'
import { uiT, uiLocale, useUiLanguage } from '../../lib/i18n.ts'
import { fields, refreshModels, saveModels, type Catalog, type CatalogModel, type Provider } from './models/catalog.ts'
import { ModelEditor } from './models/model-editor.tsx'
import { ConnectionEditor } from './models/connection-editor.tsx'
import { ConnectionWizard } from './models/connection-wizard.tsx'

type Surface = { kind: 'connection' | 'add' | 'model' | 'remove' | 'test'; provider: Provider; revision: number; model?: CatalogModel } | { kind: 'new'; revision: number } | null
const sameRoute = (a: ModelRoute | null | undefined, b: ModelRoute | null | undefined) => !!a && !!b && a.provider === b.provider && a.model === b.model

export function ProviderManager({ value, onDefault }: { value: ModelRoute | null; onDefault: (route: ModelRoute | null) => Promise<void> }) {
  useUiLanguage()
  const query = useQuery({ queryKey: ['providers'], queryFn: () => api<Catalog>('/settings/providers') }), modelQuery = useModels()
  const [view, setView] = useState<'models' | 'connections'>('models'), [search, setSearch] = useState(''), [surface, setSurface] = useState<Surface>(null), [defaultOpen, setDefaultOpen] = useState(false)
  const [defaultCandidate, setDefaultCandidate] = useState<ModelRoute | undefined>(undefined)
  const searchInput = useRef<HTMLInputElement>(null), returnToSearch = useRef(false)
  const effective = modelQuery.data?.effectiveMain, resolved = modelQuery.data?.models.find(model => sameRoute(model, effective))
  const providers = query.data?.providers ?? [], allModels = providers.flatMap(provider => provider.models.map(model => ({ provider, model })))
  const filtered = allModels.filter(({ provider, model }) => [provider.label, model.model, model.label].join(' ').toLowerCase().includes(search.toLowerCase()))
  const open = (kind: Exclude<NonNullable<Surface>['kind'], 'new'>, provider: Provider, model?: CatalogModel) => setSurface({ kind, provider, model, revision: query.data!.revision })
  return <section className="model-settings stack">
    <SettingsGroup><SettingRow kind="field" label={uiT('默认主模型')} help={uiT('新会话从这里开始，会话中可随时切换。')}><Button className="default-model-choice" onClick={() => { setDefaultCandidate(undefined); setDefaultOpen(true) }}><span><strong>{resolved?.label ?? effective?.model ?? uiT('尚未选择模型')}</strong><small>{effective && !resolved ? uiT('模型配置已不可用') : value ? uiT('个人默认') : uiT('跟随部署配置')}{resolved && !resolved.configured ? ' · ' + uiT('缺少密钥') : ''}</small></span><Settings2 size={16} /></Button></SettingRow></SettingsGroup>
    <TabGroup value={view} onChange={next => { setView(next); setSearch('') }} label={uiT('模型管理视图')} className="model-catalog-tabs" items={[{ value: 'models', label: uiT('模型') }, { value: 'connections', label: uiT('服务连接') }]}>
      <div className="model-toolbar"><div className="search-field"><Search size={16} /><Input ref={searchInput} aria-label={view === 'models' ? uiT('搜索模型') : uiT('搜索连接')} placeholder={view === 'models' ? uiT('搜索模型名称、ID 或连接') : uiT('搜索连接名称或地址')} value={search} onChange={event => setSearch(event.target.value)} /></div>{view === 'connections' || !providers.length ? <Button disabled={!query.data} onClick={() => setSurface({ kind: 'new', revision: query.data!.revision })}><Plus size={16} />{uiT('添加连接')}</Button> : <Menu label={uiT('添加模型')} trigger={<Button><Plus size={16} />{uiT('添加模型')}</Button>}><MenuLabel>{uiT('从服务连接添加')}</MenuLabel>{providers.map(provider => <MenuItem key={provider.id} onSelect={() => open('add', provider)}>{provider.label}</MenuItem>)}<MenuSeparator /><MenuItem onSelect={() => setSurface({ kind: 'new', revision: query.data!.revision })}><Plus size={15} />{uiT('添加新连接')}</MenuItem></Menu>}</div>
      <ErrorNotice error={query.error} retry={() => void query.refetch()} retrying={query.isFetching} />{query.isPending && <Loading />}
      {query.data && view === 'models' && <><div className="catalog-caption">{uiT('%{count} 个模型', { count: allModels.length })}<span>{uiT('测试状态只对应当前配置')}</span></div><div className="model-rows">{filtered.map(({ provider, model }) => <div className="model-row" key={JSON.stringify([provider.id, model.model])}><button type="button" className="model-row-main" onClick={() => open('model', provider, model)}><span className="model-row-title">{model.label || model.model}{sameRoute(effective, { provider: provider.id, model: model.model }) && <span className="model-tag">{uiT('默认')}</span>}</span><span className="model-row-meta">{provider.label}<span>·</span>{model.input?.includes('image') ? uiT('文字与图片') : uiT('文字')}{model.reasoning && <><span>·</span>{uiT('思考')}</>}</span></button><ModelState model={model} /><Button className="model-configure" tone="quiet" onClick={() => open('model', provider, model)}>{uiT('配置')}</Button><Menu label={uiT('%{name} 的模型操作', { name: model.label || model.model })}><MenuItem onSelect={() => open('test', provider, model)} disabled={!model.configured}>{uiT('测试模型')}</MenuItem><MenuItem disabled={!model.configured} onSelect={() => { setDefaultCandidate({ provider: provider.id, model: model.model }); setDefaultOpen(true) }}>{uiT('设为默认模型')}</MenuItem><MenuItem onSelect={() => open('connection', provider)}>{uiT('编辑服务连接')}</MenuItem><MenuSeparator /><MenuItem danger onSelect={() => open('remove', provider, model)}>{uiT('移除模型')}</MenuItem></Menu></div>)}</div>{!query.error && !filtered.length && <Empty title={search ? uiT('没有找到模型') : uiT('添加第一个模型')} action={search ? <Button onClick={() => setSearch('')}>{uiT('清空搜索')}</Button> : <Button onClick={() => providers[0] ? open('add', providers[0]) : setSurface({ kind: 'new', revision: query.data!.revision })}>{providers.length ? uiT('添加模型') : uiT('连接模型服务')}</Button>}>{search ? uiT('试试模型 ID 或服务连接名称。') : uiT('连接你使用的模型服务，再选择用于对话的模型。')}</Empty>}</>}
      {query.data && view === 'connections' && <><p className="catalog-caption">{uiT('一个连接共用地址、协议和密钥，可添加多个模型。')}</p><div className="model-rows">{providers.filter(provider => (provider.label + provider.connection.baseUrl).toLowerCase().includes(search.toLowerCase())).map(provider => <div className="connection-row" key={provider.id}><ConnectionLogo connection={provider.connection} label={provider.label} /><button type="button" className="model-row-main" onClick={() => open('connection', provider)}><span className="model-row-title">{provider.label}</span><span className="connection-url" title={provider.connection.baseUrl}>{provider.connection.baseUrl}</span><span className="model-row-meta">{uiT('%{count} 个模型', { count: provider.models.length })}<span>·</span>{provider.credentialConfigured ? provider.keyStored ? uiT('密钥已保存') : uiT('使用部署环境密钥') : uiT('缺少密钥')}</span></button><Button tone="quiet" onClick={() => open('connection', provider)}>{uiT('编辑')}</Button><Menu label={uiT('%{name} 的连接操作', { name: provider.label })}><MenuItem onSelect={() => open('add', provider)}>{uiT('添加模型')}</MenuItem><MenuItem danger onSelect={() => open('remove', provider)}>{uiT('删除连接')}</MenuItem></Menu></div>)}</div>{!query.error && !providers.some(provider => (provider.label + provider.connection.baseUrl).toLowerCase().includes(search.toLowerCase())) && <Empty title={search ? uiT('没有找到连接') : uiT('尚未添加服务连接')} action={search ? <Button onClick={() => setSearch('')}>{uiT('清空搜索')}</Button> : undefined} />}</>}
    </TabGroup>
    <Modal size="form" className="settings-modal" title={uiT('默认主模型')} open={defaultOpen} onOpenChange={setDefaultOpen}>{defaultOpen && <DefaultModelEditor value={value} initial={defaultCandidate} onSave={onDefault} done={() => setDefaultOpen(false)} />}</Modal>
    <Modal size={surface?.kind === 'test' || surface?.kind === 'remove' ? 'form' : 'editor'} className="settings-modal model-dialog" open={surface !== null} onOpenChange={open => { if (!open) setSurface(null) }} onCloseAutoFocus={event => { if (returnToSearch.current) { returnToSearch.current = false; event.preventDefault(); searchInput.current?.focus({ preventScroll: true }) } }} title={uiT(surface?.kind === 'new' ? '连接模型服务' : surface?.kind === 'add' ? '添加模型' : surface?.kind === 'model' ? '配置模型' : surface?.kind === 'test' ? '测试模型' : surface?.kind === 'remove' ? surface.model ? '移除模型？' : '删除连接？' : '编辑服务连接')}>
      {surface?.kind === 'new' && <ConnectionWizard revision={surface.revision} done={() => setSurface(null)} onDefault={onDefault} />}
      {surface?.kind === 'add' && <ConnectionWizard provider={surface.provider} revision={surface.revision} done={() => setSurface(null)} onDefault={onDefault} />}
      {surface?.kind === 'model' && <ModelEditor provider={surface.provider} modelId={surface.model?.model} revision={surface.revision} done={() => setSurface(null)} />}
      {surface?.kind === 'connection' && <ConnectionEditor provider={surface.provider} revision={surface.revision} done={() => setSurface(null)} />}
      {surface?.kind === 'test' && surface.model && <ModelTest provider={surface.provider} model={surface.model} revision={surface.revision} />}
      {surface?.kind === 'remove' && <RemoveModel provider={surface.provider} model={surface.model} revision={surface.revision} done={() => setSurface(null)} removed={() => { returnToSearch.current = true; setSurface(null) }} />}
    </Modal>
  </section>
}
function ModelState({ model }: { model: CatalogModel }) {
  const status = !model.configured ? 'missing' : model.check?.status ?? 'untested', Icon = status === 'passed' ? CheckCircle2 : status === 'failed' ? CircleAlert : status === 'missing' ? TriangleAlert : Circle
  return <span className={'model-state model-state-' + status} title={model.check ? uiT(model.check.message) : undefined}><Icon size={13} aria-hidden="true" />{uiT(status === 'passed' ? '测试通过' : status === 'failed' ? '测试失败' : status === 'missing' ? '缺少密钥' : '未测试')}</span>
}
function DefaultModelEditor({ value, initial, onSave, done }: { value: ModelRoute | null; initial?: ModelRoute; onSave: (route: ModelRoute | null) => Promise<void>; done: () => void }) {
  const [route, setRoute] = useState(initial ?? value), action = useAction(), dirty = JSON.stringify(route) !== JSON.stringify(value)
  return <EditorForm className="stack" dirty={dirty} busy={action.busy} onSubmit={event => { event.preventDefault(); void action.run(async () => { await onSave(route); done() }) }}><p className="muted">{uiT('新会话默认使用这个模型，会话中可随时更换。')}</p><ModelPicker value={route} onChange={setRoute} inheritLabel={uiT('跟随部署配置')} inheritDetail={uiT('使用部署文件指定的默认模型')} /><ErrorNotice error={action.error} /><div className="form-actions"><CancelButton onCancel={done} /><Button type="submit" tone="primary" disabled={action.busy || !dirty}>{uiT('保存默认模型')}</Button></div></EditorForm>
}
function ModelTest({ provider, model, revision }: { provider: Provider; model: CatalogModel; revision: number }) {
  const [result, setResult] = useState(model.check), action = useAction()
  return <EditorForm className="stack" busy={action.busy} onSubmit={event => { event.preventDefault(); void action.run(async () => { setResult(await api<ModelCheck>(`/settings/providers/${encodeURIComponent(provider.id)}/test`, 'POST', { expectedRevision: revision, model: model.model })); await refreshModels() }) }}><div className="connection-caption">{provider.label}<strong>{model.label || model.model}</strong></div><p className="muted">{uiT('测试会发送一条简短请求，可能消耗少量额度。')}</p>{result && <StatusNotice compact tone={result.status === 'failed' ? 'error' : 'success'} title={uiT(result.status === 'failed' ? '连接测试未通过' : '连接测试通过')} details={uiT(result.message)}><small>{new Date(result.checkedAt).toLocaleString(uiLocale())} · {(result.durationMs / 1000).toFixed(1)}s</small></StatusNotice>}<ErrorNotice error={action.error} /><div className="form-actions"><Button type="submit" tone="primary" disabled={action.busy}>{action.busy ? uiT('正在测试…') : result ? uiT('重新测试') : uiT('开始测试')}</Button></div></EditorForm>
}
function RemoveModel({ provider, model, revision, done, removed }: { provider: Provider; model?: CatalogModel; revision: number; done: () => void; removed: () => void }) {
  const action = useAction()
  return <EditorForm className="stack" busy={action.busy} onSubmit={event => { event.preventDefault(); void action.run(async () => { if (model) await saveModels(provider, revision, provider.models.filter(item => item.model !== model.model).map(fields)); else { await api(`/settings/providers/${encodeURIComponent(provider.id)}`, 'DELETE', { expectedRevision: revision }); await refreshModels() } removed() }) }}><p>{model ? uiT('将从“%{name}”移除这个模型，服务连接和密钥会保留。', { name: provider.label }) : uiT('将删除“%{name}”及其 %{count} 个模型和保存的密钥。', { name: provider.label, count: provider.models.length })}</p>{model && <strong>{model.label || model.model}</strong>}<p className="muted">{uiT('引用这些模型的默认设置、Writer、任务子代理和会话需要重新选择模型；历史记录会保留。')}</p><ErrorNotice error={action.error} /><div className="form-actions"><Button onClick={done}>{uiT('取消')}</Button><Button type="submit" tone="danger" disabled={action.busy}>{uiT(model ? '移除模型' : '删除连接')}</Button></div></EditorForm>
}
