import { ContentImage } from '../components/content-image.tsx'
import { uiT, uiLocale, useUiLanguage } from "../lib/i18n.ts"
import { useState } from 'react'
import { useQuery } from '@tanstack/react-query'
import { Plus, Download, Eye, Library, Search, Pencil, Trash2, Star, UserRound } from 'lucide-react'
import type { AssetKind } from '../../../../packages/rp-core/src/types.ts'
import { ASSET_KINDS } from '../../../../packages/rp-core/src/types.ts'
import { api, ApiError, useAction, useAssetCatalog, type AssetItem } from '../lib/api.ts'
import { assetLabels } from '../components/selectors.tsx'
import { Button, Check, Empty, ErrorNotice, Input, Loading, Menu, MenuItem, Modal, TabGroup } from '../components/ui.tsx'
import { PageHeader } from '../components/shell-context.tsx'
import { ImportAssets } from './library/import-assets.tsx'
import { AssetEditorDialog, refreshAssets } from './library/asset-editor.tsx'
import { AssetDetailsById } from '../components/asset-details.tsx'

export function LibraryPage() {
  useUiLanguage()
  const [preview, setPreview] = useState<string | null>(null)
  const [kind, setKind] = useState<AssetKind>('character'), [q, setQ] = useState(''), [offset, setOffset] = useState(0), [editing, setEditing] = useState<string | 'new' | null>(null), [removing, setRemoving] = useState<AssetItem | null>(null), [associated, setAssociated] = useState(true), [importing, setImporting] = useState(false)
  const catalog = useAssetCatalog(kind, q, offset), action = useAction()
  const defaults = useQuery({ queryKey: ['defaults'], queryFn: () => api<{ defaults: { persona: string; preset: string; writingStyle: string } }>('/assets/defaults') })
  const duplicateId = action.error instanceof ApiError && action.error.code === 'DUPLICATE_ASSET' && action.error.details !== null && typeof action.error.details === 'object' && 'assetId' in action.error.details ? String(action.error.details.assetId) : undefined
  return <div className="page-screen"><PageHeader title={uiT("角色与资料")} /><div className="page-content library-page"><div className="page-inner"><div className="page-heading"><div className="section-heading"><div><h2>{uiT("共享资料")}</h2><p className="muted">{uiT("管理角色、参考资料和写作偏好，在会话间复用。")}</p></div><div className="page-actions"><ImportAssets kind={kind} refresh={refreshAssets} onBusy={setImporting} open={(id, targetKind) => { setKind(targetKind); setEditing(id) }} /><Button tone="primary" onClick={() => setEditing('new')}><Plus size={17} />{uiT(`创建${assetLabels[kind]}`)}</Button></div></div></div>
    <TabGroup value={kind} onChange={value => { setKind(value); setOffset(0); setQ(''); action.clear() }} items={ASSET_KINDS.map(value => ({ value, label: uiT(assetLabels[value]), disabled: importing }))} label={uiT("资料分类")}>
    <div className="library-toolbar"><div className="search-field library-search"><Search size={17} /><Input aria-label={uiT("搜索资料库")} placeholder={uiT("搜索%{v0}…", { v0: uiT(assetLabels[kind]) })} value={q} onChange={event => { setQ(event.target.value); setOffset(0) }} /></div>{catalog.data && <span>{catalog.data.total} {uiT(" 份资料")}</span>}</div>
    <ErrorNotice error={action.error ?? catalog.error} retry={!action.error && catalog.error ? () => void catalog.refetch() : undefined} retrying={catalog.isFetching} />{duplicateId && <Button onClick={() => setEditing(duplicateId)}>{uiT("打开已导入的资料")}</Button>}
    {catalog.isPending && <Loading />}
    <div className={`asset-grid${kind === 'character' || kind === 'persona' ? '' : ' asset-list'}`}>{catalog.data?.assets.map(asset => <article className={`asset-card asset-${kind}`} key={asset.id}><button className="asset-open" aria-label={uiT("编辑%{v0}：%{v1}", { v0: uiT(assetLabels[kind]), v1: asset.name })} onClick={() => setEditing(asset.id)}>{asset.avatarFileId ? <ContentImage className="asset-cover" src={`/api/files/${asset.avatarFileId}/content`} alt={asset.name} loading="lazy" /> : <span className="asset-cover asset-cover-empty">{kind === 'character' || kind === 'persona' ? <UserRound size={26} strokeWidth={1.3} /> : <Library size={26} strokeWidth={1.3} />}</span>}<div className="asset-card-text"><h2>{asset.name}</h2><p>{uiT(assetLabels[kind])} · {new Date(asset.updatedAt).toLocaleDateString(uiLocale())}{asset.contentCharacters != null && uiT(" · %{v0} 字", { v0: asset.contentCharacters.toLocaleString(uiLocale()) })}</p>{asset.description && <p className="asset-description">{asset.description}</p>}{(kind === 'persona' || kind === 'preset' || kind === 'writingStyle') && defaults.data?.defaults[kind] === asset.id && <small className="default-badge">{uiT("新会话默认")}</small>}</div></button><Menu label={uiT("%{v0}的操作", { v0: asset.name })}><MenuItem onSelect={() => setPreview(asset.id)}><Eye size={15} />{uiT("查看详情")}</MenuItem><MenuItem onSelect={() => setEditing(asset.id)}><Pencil size={15} />{uiT("编辑")}</MenuItem>{(kind === 'persona' || kind === 'preset' || kind === 'writingStyle') && <MenuItem onSelect={() => void action.run(async () => { await api('/assets/defaults', 'PUT', { kind, assetId: asset.id }); await refreshAssets() })}><Star size={15} />{uiT("设为新会话默认")}</MenuItem>}<MenuItem onSelect={() => { location.href = `/api/assets/${asset.id}/export?format=json` }}><Download size={15} />{uiT("导出 JSON")}</MenuItem>{kind === 'character' && <MenuItem onSelect={() => { location.href = `/api/assets/${asset.id}/export?format=png` }}><Download size={15} />{uiT("导出 PNG 角色卡")}</MenuItem>}<MenuItem danger onSelect={() => { setAssociated(true); setRemoving(asset) }}><Trash2 size={15} />{uiT("删除")}</MenuItem></Menu></article>)}</div>
    {!catalog.error && catalog.data?.total === 0 && <Empty icon={<Library size={34} strokeWidth={1.3} />} title={q ? uiT("没有找到这份资料") : uiT("还没有%{v0}", { v0: uiT(assetLabels[kind]) })} action={q ? <Button onClick={() => setQ('')}>{uiT("清空搜索")}</Button> : <Button onClick={() => setEditing('new')}>{uiT("创建第一份")}</Button>}>{q ? uiT("试试其他关键词。") : kind === 'character' ? uiT("可以导入 JSON 或 PNG 角色卡，也可以从头创建角色。") : uiT("先保存一份资料，再把它加入会话。")}</Empty>}
    {catalog.data && catalog.data.total > 50 && <div className="pagination"><Button disabled={offset === 0} onClick={() => setOffset(value => Math.max(0, value - 50))}>{uiT("上一页")}</Button><span>{uiT("共 ")}{catalog.data.total} {uiT(" 份")}</span><Button disabled={catalog.data.nextOffset == null} onClick={() => setOffset(catalog.data!.nextOffset!)}>{uiT("下一页")}</Button></div>}

    </TabGroup></div></div>
    <Modal open={preview !== null} onOpenChange={open => { if (!open) setPreview(null) }} title={uiT("%{v0}详情", { v0: uiT(assetLabels[kind]) })} size="editor">{preview && <div className="stack"><AssetDetailsById id={preview} /><div className="form-actions"><Button onClick={() => { setEditing(preview); setPreview(null) }}><Pencil size={15} />{uiT("编辑资料")}</Button><a className="button" href={`/api/assets/${preview}/export?format=json`}>{uiT("导出 JSON")}</a>{kind === 'character' && <a className="button" href={`/api/assets/${preview}/export?format=png`}>{uiT("导出 PNG 角色卡")}</a>}</div></div>}</Modal>
    <AssetEditorDialog id={editing} kind={kind} onClose={() => setEditing(null)} />
    <Modal size="compact" open={removing !== null} onOpenChange={open => { if (!open) setRemoving(null) }} title={uiT("删除这份资料？")}><p>{uiT("删除“")}{removing?.name}{uiT("”后，引用它的会话将无法继续读取这份资料。已经生成的正文会保留。")}</p>{removing?.kind === 'character' && <Check label={uiT("同时删除随这张卡导入的关联世界书")} checked={associated} onChange={event => setAssociated(event.target.checked)} />}<ErrorNotice error={action.error} /><div className="form-actions"><Button onClick={() => setRemoving(null)}>{uiT("保留")}</Button><Button tone="danger" disabled={action.busy} onClick={() => void action.run(async () => { const result = await api<{ associatedFailures: { name: string }[] }>(`/assets/${removing!.id}`, 'DELETE', { expectedRevision: removing!.revision, ...(removing!.kind === 'character' ? { removeAssociated: associated } : {}) }); setRemoving(null); await refreshAssets(); if (result.associatedFailures.length) throw new Error(uiT("角色卡已删除，但以下关联世界书未能删除：%{v0}", { v0: result.associatedFailures.map(item => item.name).join('、') })) })}>{uiT("删除资料")}</Button></div></Modal>
  </div>
}
